spring:
  profiles:
    active: teleport

logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
      hibernate: WARN

core:
  initial-valence: 1.0
  initial-dominance: 1.0

---

spring:
  profiles: teleport

count-player: 2
actions:
  - name: "Kick"
    valence: 2.0
    dominance: 2.0

  - name: "Save"
    valence: 2.0
    dominance: 2.0

  - name: "Greet"
    valence: 2.0
    dominance: 2.0

  - name: "Activate"
    valence: 2.0
    dominance: 2.0

  - name: "Deactivate"
    valence: 2.0
    dominance: 2.0

  - name: "ExitTP"
    valence: 2.0
    dominance: 2.0

  - name: "TakeOff"
    valence: 2.0
    dominance: 2.0

  - name: "Spawned"
    valence: 2.0
    dominance: 2.0

  - name: "Move"
    valence: 2.0
    dominance: 2.0

  - name: "EnterTP"
    valence: 2.0
    dominance: 2.0

---

spring:
  profiles: telegram

