spring:
  profiles:
    active: teleport

logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
      hibernate: WARN

game-config-location: "/Users/daniilazarnov/config/game_config.json"
client-url: "http://localhost:8081/teleport"