logging:
  level:
    root: INFO
    org:
      springframework:
        web: WARN
      hibernate: WARN

paradigm:
  config-location: "/Users/daniilazarnov/config/game_config.json"
  url: "http://localhost:8081/teleport/"

storage:
  url: "http://localhost:8082/storage"
