spring:
  profiles:
    active: calculator

logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
      hibernate: WARN

---

spring:
  profiles: calculator

date-time-formatter: "M/dd/yyyy HH:mm:ss:[SSS][SS][S]"
csv-delimiter: ","

before-calc-location: "/Users/daniilazarnov/logs/before"
after-calc-location: "/Users/daniilazarnov/logs/after"

initial-valence: 0.0
initial-dominance: 0.0

system-actions:
  - "Spawned"
  - "BeginRound"
  - "EndRound"
  - "Spawned"
  - "Reset"

actions:
  - name: "Kick"
    valence: -0.2
    dominance: 0.2
    type: "NORMAL"

  - name: "Ask"
    valence: 0.1
    dominance: -0.1
    type: "NORMAL"

  - name: "Saved"
    valence: 1.8
    dominance: -0.15
    type: "NORMAL"

  - name: "Thank"
    valence: 0.1
    dominance: -0.2
    type: "NORMAL"

  - name: "Greet"
    valence: 0.1
    dominance: 0.15
    type: "NORMAL"

  - name: "Activated"
    valence: 0.5
    dominance: 0.0
    type: "ALL"

  - name: "Deactivated"
    valence: -1.1
    dominance: 0.0
    type: "ALL"

  - name: "ExitTP"
    valence: -0.1
    dominance: 0.0
    type: "ALL"

  - name: "TakeOff"
    valence: 2.7
    dominance: 0.6
    type: "SELF"

  - name: "Moved"
    valence: 0.0
    dominance: 0.0
    type: "SELF"

  - name: "Move"
    valence: 0.0
    dominance: 0.0
    type: "SELF"

  - name: "EnterTP"
    valence: 0.1
    dominance: 0.0
    type: "SELF"

  - name: "Escaped"
    valence: -3.0
    dominance: 1.0
    type: "SELF"

  - name: "Escape"
    valence: -3.0
    dominance: 1.0
    type: "SELF"

  - name: "ConfirmedHuman"
    valence: 0.1
    dominance: 0.0
    type: "NORMAL"

  - name: "Shoot"
    valence: -0.6
    dominance: 0.4
    type: "NORMAL"

  - name: "Heal"
    valence: 0.9
    dominance: -0.2
    type: "NORMAL"

  - name: "ConfirmedBot"
    valence: 0.1
    dominance: 0.15
    type: "NORMAL"
