spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  http:
    multipart:
      enabled: false

logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
      hibernate: WARN

server:
  port: 8081

storage:
  location: "upload-dir"
