logging:
  level:
    root: INFO
    org:
      springframework:
        web: WARN
      hibernate: WARN

server:
  port: 8082

date-time-formatter: "M/dd/yyyy HH:mm:ss:[SSS][SS][S]"
csv-delimiter: ","

before-calc-location: "/Users/daniilazarnov/logs/before"
after-calc-location: "/Users/daniilazarnov/logs/after"
game-config-location: "/Users/daniilazarnov/config/game_config.json"
