logging:
  level:
    root: INFO
    org:
      springframework:
        web: WARN
      hibernate: WARN

server:
  port: 8082

parser:
  formatter: "M/dd/yyyy HH:mm:ss:[SSS][SS][S]"
  delimiter: ","
  config-location: "/Users/daniilazarnov/config/game_config.json"
  bot-url: "http://localhost:8080/calculate"

storage:
  before-location: "/Users/daniilazarnov/logs/before"
  after-location: "/Users/daniilazarnov/logs/after"
